const  colleges = [
  "CU Kashmir",
  "Institute of Hotel Management, Rajbagh, Srinagar",
  "National Institute of Fashion Technology, Ompora, Budgam",
  "Govt. Degree College Magam, Beeru",
  "Govt. Degree College, Budgam",
  "Govt. Degree College for Women, Baramulla",
  "Govt. Degree College for Women, Anantanag",
  "Islamia College of Science and Commerce Hawal",
  "Govt. Degree College, Ganderbal",
  "UIET Chandigarh",
  "Dr HSJ Institute of Dental Sciences- PU Chandigarh (IDS)",
  "CSIR-Central Scientific Instruments Organisation, Chandigarh (CSIO)",
  "Punjab Engineering College (Deemed to be University), Chandigarh (PEC)",
  "IIT Roorkee",
  "College of Technology, Gbpuat, Pantnagar",
  "National Institute of Technology (NIT), Uttarakhand",
  "Indian Institute Management (IIM), Kashipur",
  "DU Delhi",
  "Jamia Millia Islamia, New Delhi",
  "Islamic University of Science and Technology J&K",
  "IIT Delhi",
  "IIT Mandi",
  "Indraprastha Institute of Information Technology Delhi",
  "Indira Gandhi Delhi Technical University for Women",
  "SPA Delhi",
  "Ambedkar University, Delhi",
  "School of Planning and Architecture, Vijayawada",
  "School of Planning and Architecture, Bhopal",
  "UoR Jaipur",
  "Malviya National Institute of Technology, Jaipur",
  "Lachoo Memorial College of Science & Technology, Jodhpur",
  "Birla Institute of Scientific Research, Jaipur",
  "IIT Kanpur",
  "Sanjay Gandhi PG Institute of Medical Sciences (SGPGI), Lucknow",
  "Indian Agricultural Research Institute (IARI), New Delhi",
  "Harcourt Butler Technological University (HBTU), Kanpur",
  "IIT BHU & BHU",
  "University of Allahbad",
  "Indian Institute of Information Technology, Allahabad",
  "Motilal Nehru National Institute of Technology, Allahabad",
  "IIT Guwahati",
  "Indian Institute of Information Technology, Manipur",
  "National Institute of Technology Meghalaya",
  "Assam Agricultural University Jorhat, Assam",
  "NEHU Shillong",
  "St. Mary’s College (SMC), Shillong",
  "St. Anthony’s College (SAC), Shillong",
  "Indian Institute of Information Technology, Guwahati (IIITG)",
  "RDU Jabalpur",
  "St. Aloysius’ College (Autonomous) and St. Aloysius Institute of Technology, Jabalpur",
  "Biotechnology Centre Jawaharlal Nehru Krishi Vishwavidyalaya (JNKVV), Jabalpur",
  "India Institute of Information Technology Design & Manufacturing (IIITDM), Jabalpur",
  "GTU Ahmedabad",
  "Government Engineering College, Modasa",
  "Dr. S. & S. S. Ghandhy Government Engineering College – Surat",
  "A.V. Parekh Technical Institute – Rajkot",
  "IIT Kharagpur",
  "IIEST Shibpur",
  "NIT Jamshedpur",
  "NIT Patna",
  "IIT Bhubaneswar",
  "College of Engineering & Technology (CET), Bhubaneswar",
  "Kendriya Vidyalaya School (KV) – No.1 Bhubaneswar",
  "Bhubanananda Orissa School of Engineering (BOSE), Cuttack",
  "Ravenshaw University (Psychology & Philosophy Department), Cuttack",
  "IIT Bombay",
  "The National Innovation Foundation (NIF) – India Ahmedabad Gujarat",
  "Dr. Balasaheb Sawantkonkan Krishi Vidyapeeth Dapoli, Maharashtra",
  "College of Engineering Pune",
  "SPPU Pune",
  "Padmashri Vikhe Patil College of Arts Science & Commerce Pravaranagar Loni, Ahmednagar",
  "Maratha Vidya Prasarak Samaj College of Architecture and Centre for Design Gangapur Road, Nashik",
  "Indian Institute of Education, Vigyan Ashram, Pabal",
  "IIT Hyderabad",
  "IIIT Hyderabad",
  "IIITDM Kancheepuram",
  "IIIT Sricity",
  "JNTU Kakinada",
  "IIIT, Rk Valley",
  "Acharya Nagarjuna University",
  "IIIT, Nuzivid",
  "IISc Bangalore",
  "University Visvesvaraya College of Engineering, Bangalore",
  "National Institute of Technology Calicut, Kerala",
  "National Institute of Technology, Surathkal, Karnataka",
];

export default colleges;