POST http://localhost:4001/hackathon
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2MyOWY2MzlmOGEwYWQ2NWM4ZTk3MWIiLCJpYXQiOjE3NDA5MDk0ODMsImV4cCI6MTc0MDk5NTg4M30.Tc919_Vb5wxY8roFSH7GGgi1TXuhJxy0Rbl6vhyy_n4  

{
  "teamMembers": [
    {
      "tzkid": "tzk250027",
      "name": "Nayak ",
      "phoneNumber": "7337273492"
    },
    {
      "tzkid": "tzk250019",
      "name": "Pallapu Siva Santosh",
      "phoneNumber": "9059470520"
    }
    
  ],
  "projectName": "Robothon",
  "abstract": "Robothon",
  "file": "Robothon",
  "problemStatementNumber": 1
}

###
POST http://localhost:4001/hackathon/addByAdmin
Content-Type: application/json

{
  "teamMembers": [
    {
      "tzkid": "tzk250072",
      "name": "Alice Johnson",
      "phoneNumber": "9876543210"
    },
    {
      "tzkid": "tzk250072",
      "name": "Bob Smith",
      "phoneNumber": "9876543211"
    }
  ],
  "projectName": "AI-Based Crop Monitoring",
  "abstract": "This project leverages AI and IoT sensors to monitor crop health in real-time, enhancing agricultural efficiency.",
  "file": "https://example.com/uploads/project-file.pdf",
  "problemStatementNumber": 3
}
