POST http://localhost:4001/hackathon
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzkzODEzNDhmZjcwMTA0ZjM1NmU2ODAiLCJpYXQiOjE3NDA0Njk3MzEsImV4cCI6MTc0MDU1NjEzMX0.2-cI7JwQsCh9qKhoc7a17FyaaFcE3CEemDcFHAEUdMA

{
  "teamMembers": [
    {
      "tzkid": "tzk250013",
      "name": "Alice Johnson",
      "phoneNumber": "9876543210"
    },
    {
      "tzkid": "tzk250073",
      "name": "Bob Smith",
      "phoneNumber": "9876543211"
    }
  ],
  "projectName": "RoboTHOn",
  "abstract": "RoboTHOn",
  "file": "RoboTHOn.pdf",
  "problemStatementNumber": 3
}

###
POST http://localhost:4001/hackathon/addByAdmin
Content-Type: application/json

{
  "teamMembers": [
    {
      "tzkid": "tzk250072",
      "name": "Alice Johnson",
      "phoneNumber": "9876543210"
    },
    {
      "tzkid": "tzk250072",
      "name": "Bob Smith",
      "phoneNumber": "9876543211"
    }
  ],
  "projectName": "AI-Based Crop Monitoring",
  "abstract": "This project leverages AI and IoT sensors to monitor crop health in real-time, enhancing agricultural efficiency.",
  "file": "https://example.com/uploads/project-file.pdf",
  "problemStatementNumber": 3
}
